### ISSUE TITLE
CrowdinTranslate does not support newer versions of gradle

### ISSUE THREAD

**Issue by Hugman76** [gbl/CrowdinTranslate#5]
CrowdinTranslate does not support newer versions of gradle, which are needed for modding in 1.17

```
> Failed to apply plugin class 'de.guntram.mcmod.crowdintranslate.GradlePlugin.CrowdinTranslatePlugin'.
   > Could not create task ':downloadTranslations'.
      > Cannot create task ':downloadTranslations' of type 'DownloadTask' as directly extending AbstractTask is not supported.
```

also see: https://docs.gradle.org/current/userguide/upgrading_version_6.html#using_abstracttask

edit: I tried to do such an update in #7

**Comment by Hugman76** [comment]
Fixed with PR #7, but isnt's available on the maven yet

**Comment by gbl** [comment]
Yes, I'm fighting a few other issues: a few things have been renamed in `ReloadableResourceManager`, updating my toolchain to gradle 7 and Java 16 broke a few things, I need to replace the maven plugin by maven-publish because gradle 7 doesn't support the old one any more, ... - expect a maven publish in a few hours hopefully.

**Comment by gbl** [comment]
There's still a bug that seems to be in loom, see https://discord.com/channels/507304429255393322/842691768175951942/850325622752280606 - it creates a dependency that's wrong. I "fixed" that by manually removing the dependency from the pom file, and published to maven (http://minecraft.guntram.de/maven/de/guntram/mcmod/crowdin-translate/1.3+1.17-pre5/). Use with caution but I'm happy to get feedback if it works for you.

**Comment by Hugman76** [comment]
It works wonderfully! Thanks!
